spring:
  # --- ?????? ?? ?? ---
  datasource:
    # PostgreSQL JDBC ???? ??? ??
    driver-class-name: org.postgresql.Driver
    # ?????? ?? URL
    url: jdbc:postgresql://localhost:5432/smartfarm
    # ??? ??
    username: postgre
    # ??? ????
    password: 1234

  # --- JPA ? ?????? ?? ---
  jpa:
    # ?????? ??(Dialect) ??
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ddl-auto: ??? ???? ???? DB ???? ???? ???? ?? (?? ??!)
      # create: ?????? ?? ? ?? ???? ?? ???? ?? ?? (?? ???, ??? ?? ???)
      # update: ??? ??? ???? ???? ?? (????? ??, ????? ?? ?? ??)
      # validate: ???? ???? ?????? ??. ??? ?? ??
      # none: ???? ?? ?? (?? ???? ??)
      # >> ?? ?? ??? 'create'? ???? ???? ?? ????,
      # >> ? ???? 'validate'? 'none'?? ?? ???
      ddl-auto: create
    # JPA? ???? SQL ??? ??? ???? ??
    show-sql: true
    properties:
      hibernate:
        # ???? SQL? ??? ???
        format_sql: true