spring:

  # mqtt
  mqtt:
    url: tcp://localhost:1883  # 로컬 Mosquitto 브로커 주소 (환경에 맞게 변경)
    client-id: spring-boot-server

  # --- ?????? ?? ?? ---
  datasource:
    # PostgreSQL JDBC ???? ??? ??
    driver-class-name: org.postgresql.Driver
    # ?????? ?? URL
    url: jdbc:postgresql://localhost:5432/farmtastic
    # ??? ??
    username: postgres
    # ??? ????
    password: 1234

  # --- JPA ? ?????? ?? ---
  jpa:    # ?????? ??(Dialect) ??
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ddl-auto: ??? ???? ???? DB ???? ???? ???? ?? (?? ??!)
      # create: ?????? ?? ? ?? ???? ?? ???? ?? ?? (?? ???, ??? ?? ???)
      # update: ??? ??? ???? ???? ?? (????? ??, ????? ?? ?? ??)
      # validate: ???? ???? ?????? ??. ??? ?? ??
      # none: ???? ?? ?? (?? ???? ??)
      # >> ?? ?? ??? 'create'? ???? ???? ?? ????,
      # >> ? ???? 'validate'? 'none'?? ?? ???
      ddl-auto: create
    # JPA? ???? SQL ??? ??? ???? ??
    show-sql: true
    properties:
      hibernate:
        # ???? SQL? ??? ???
        format_sql: true
  sql:
    init:
      mode: always # sql 스크립트를 항상 실행하도록 설정